# OpenMM Tutorial

Platform for molecular dynamics. Customizable, open-source, supports CUDA, etc.

OpenMM has weird documentation. Often the first link if you google openmm points you to an old version (7.0.0). Look for the 8.1.0 version if you are up to date.

## Imports

Along with the main openmm import, there are two libraries that are particularly useful: openmm.app and openmm.unit. openmm.unit is appropriately named and allows users to define simulations in the unit system they prefer.

openmm.app is a set of libraries for the high-level application layer. This provides easier interfacing with your code to tune general parameters and run simulations. We will focus on this to begin, and we will return to the lower-level libraries in openmm later in the tutorial.

In [1]:
import openmm as mm
import openmm.app as app
import openmm.unit as u
import numpy as np

## Input structures and forcefields

OpenMM supports multiple types of input files. The most familiar and useful for us is the PDB filetype, though .gro (Gromacs), .inpcrd/.prmtop (AMBER), and .psf (CHARMM) are also used.$^*$ A PDB file is read using the application layer, and the topology and coordinates are stored in a PDBFile object.


###### $^*$ These usually require both coordinate and topology files, and the system is created on the topology object.

In [2]:
pdb = app.PDBFile("alanine-dipeptide.pdb")
print(pdb.topology)
print(pdb.positions)

<Topology; 1 chains, 3 residues, 22 atoms, 21 bonds>
[Vec3(x=0.2, y=0.1, z=-0.0), Vec3(x=0.2, y=0.209, z=0.0), Vec3(x=0.1486, y=0.24540000000000003, z=0.08900000000000001), Vec3(x=0.1486, y=0.24540000000000003, z=-0.08900000000000001), Vec3(x=0.3427, y=0.2641, z=-0.0), Vec3(x=0.43910000000000005, y=0.1877, z=-0.0), Vec3(x=0.35550000000000004, y=0.397, z=-0.0), Vec3(x=0.27330000000000004, y=0.4556, z=-0.0), Vec3(x=0.4853, y=0.46140000000000003, z=-0.0), Vec3(x=0.5408000000000001, y=0.4316, z=0.08900000000000001), Vec3(x=0.5660999999999999, y=0.42210000000000003, z=-0.1232), Vec3(x=0.5123000000000001, y=0.4521, z=-0.21309999999999998), Vec3(x=0.663, y=0.47190000000000004, z=-0.1206), Vec3(x=0.5809000000000001, y=0.31410000000000005, z=-0.12410000000000002), Vec3(x=0.47130000000000005, y=0.6129, z=0.0), Vec3(x=0.36010000000000003, y=0.6653, z=0.0), Vec3(x=0.5846, y=0.6835, z=0.0), Vec3(x=0.6737000000000001, y=0.6359, z=-0.0), Vec3(x=0.5846, y=0.8284000000000001, z=0.0), Vec3(x=0.4819, y=0

To change your unit system, use the .value_in_unit() method. This gives the number in the new units, but it doesn't include the unit. Multiply by openmm.unit.(your_unit) to reintroduce it.

In [3]:
print(pdb.topology.getPeriodicBoxVectors()) # get box vectors in nm
print(pdb.topology.getPeriodicBoxVectors().value_in_unit(u.angstrom) * u.angstrom) # get box vectors in angstroms

(Vec3(x=10.0, y=0.0, z=0.0), Vec3(x=0.0, y=10.0, z=0.0), Vec3(x=0.0, y=0.0, z=10.0)) nm
(Vec3(x=100.0, y=0.0, z=0.0), Vec3(x=0.0, y=100.0, z=0.0), Vec3(x=0.0, y=0.0, z=100.0)) A


Forcefields are specified with their corresponding XML files and can be called with the ForceField class in the application layer. Many forcefields, such as amber14 shown below, are included with OpenMM and do not require the XML file where you are running the simulation.

In [4]:
forcefield = app.ForceField('amber14-all.xml')

Many times, water models are separated from the main forcefield and should be called separately (e.g. forcefield=app.ForceField('amber14-all.xml', 'amber14/tip3p.xml')). This lends flexibility in the choice of water model (implicit vs explicit, different methods, etc.). http://docs.openmm.org/latest/userguide/application/02_running_sims.html#force-fields provides an overview of a couple forcefields built into OpenMM. Note that some models require the topology to be adjusted to account for waters in the system.

## System objects

The System defines what you are simulating using the forcefield, topology, nonbonded considerations, and other parameters depending on the forcefield you use. It is created by calling .createSystem() on your forcefield.

In [5]:
system = forcefield.createSystem(pdb.topology,
                                 nonbondedMethod=app.NoCutoff, # implies non-periodicity, isolated box in vacuum
                                 constraints=app.HBonds)

If simulating some bulk periodic system: to prevent issues with periodic images, the nonbondedCutoff must be less than $\frac{1}{2}({\rm box~vectors})$.

## Platform objects

On what hardware do you want to simulate your system? There are four options provided by OpenMM, but only two are worth considering for our uses: CUDA and CPU.$^*$ There are two options to implicitly choose a platform. (1) OpenMM defaults to the fastest option available, and (2) you can set the OPENMM_DEFAULT_PLATFORM environment variable to your choice.

Alternatively, to explicitly specify on which device you would like to run the calculations, simply do

###### $^*$ The other platforms are Reference and OpenCL. Reference is mainly a tool for writing your own platform and does not optimize performance. OpenCL works with GPUs and CPUs, is written in OpenCL, and is useful if you're working with non-Nvidia graphics cards.

In [6]:
platform = mm.Platform.getPlatformByName('CPU') # 'CUDA' if a GPU is available

## Integrators, thermostats, and barostats
For a list of available integrators, see http://docs.openmm.org/latest/userguide/application/02_running_sims.html#integrators.

#### NVE integrators, thermostats
E.g. VerletIntegrator

You can add a thermostat to these integrators to perform NVT simulations, but Langevin integrators are preferred. To add the thermostat, apply .addForce(your_thermostat) to the system object.

In [7]:
# way to remove forces (e.g. thermostat) from the system
def manual_remove_force(system, force_object):
    for i, force in enumerate(system.getForces()):
        if f'{force}'[0:50] == f'{force_object}'[0:50]:
            system.removeForce(i)
            return True
    return False

In [8]:
nve_integrator = mm.VerletIntegrator(0.001*u.picoseconds)

thermostat = mm.AndersenThermostat(298.15*u.kelvin,
                                   1.0/u.picosecond)

manual_remove_force(system, thermostat)

system.addForce(thermostat)
print(system.getForces()[-1])

<openmm.openmm.AndersenThermostat; proxy of <Swig Object of type 'OpenMM::AndersenThermostat *' at 0x10f173030> >


#### NVT integrators
Langevin Middle Integrator: thermostat built into this, good for NVT simulations.


#### NPT simulations
To run NPT simulations, you can add a barostat. Multiple kinds are built into OpenMM: isotropic, anisotropic, specifically for membranes, http://docs.openmm.org/development/api-python/library.html#forces. Note: the system must be periodic to use a barostat.

Like thermostats, barostats need to be added to the system as forces.

In [9]:
# remove thermostat if we use Langevin integrator
manual_remove_force(system, thermostat)
print(system.getForces()) # check that the thermostat is removed

integrator = mm.LangevinMiddleIntegrator(300 * u.kelvin,           # temperature of the heat bath
                                         1.0 / u.picosecond,       # friction coefficient
                                         2.0 * u.femtosecond)      # integration timestep

barostat = mm.MonteCarloBarostat(1.0 * u.bar,       # pressure
                                 300 * u.kelvin,    # temperature - match with integrator
                                 25)                # frequency of volume change attempts in number of time steps

manual_remove_force(system, barostat) # prevent adding a second barostat if cell rerun

system.addForce(barostat)
print(system.getForces()[-1])

[<openmm.openmm.HarmonicBondForce; proxy of <Swig Object of type 'OpenMM::HarmonicBondForce *' at 0x10f173240> >, <openmm.openmm.HarmonicAngleForce; proxy of <Swig Object of type 'OpenMM::HarmonicAngleForce *' at 0x10f173210> >, <openmm.openmm.PeriodicTorsionForce; proxy of <Swig Object of type 'OpenMM::PeriodicTorsionForce *' at 0x10f1732d0> >, <openmm.openmm.NonbondedForce; proxy of <Swig Object of type 'OpenMM::NonbondedForce *' at 0x10f173360> >, <openmm.openmm.CMMotionRemover; proxy of <Swig Object of type 'OpenMM::CMMotionRemover *' at 0x10f1733f0> >]
<openmm.openmm.MonteCarloBarostat; proxy of <Swig Object of type 'OpenMM::MonteCarloBarostat *' at 0x10f173540> >


Let's remove the barostat for now and just work with the NVT ensemble.

In [10]:
manual_remove_force(system, barostat)
print(system.getForces()) # check that the barostat is removed

[<openmm.openmm.HarmonicBondForce; proxy of <Swig Object of type 'OpenMM::HarmonicBondForce *' at 0x12ea0f0c0> >, <openmm.openmm.HarmonicAngleForce; proxy of <Swig Object of type 'OpenMM::HarmonicAngleForce *' at 0x12ea0f600> >, <openmm.openmm.PeriodicTorsionForce; proxy of <Swig Object of type 'OpenMM::PeriodicTorsionForce *' at 0x12ea0fb70> >, <openmm.openmm.NonbondedForce; proxy of <Swig Object of type 'OpenMM::NonbondedForce *' at 0x12ea0fba0> >, <openmm.openmm.CMMotionRemover; proxy of <Swig Object of type 'OpenMM::CMMotionRemover *' at 0x12ea0f4e0> >]


#### Custom integrators
Instead of using an established integrator, you can also create your own. One example of this utility is with separated timescales; if you need to integrate over a fast process and a slow one, you can write an integrator that accomplishes this task efficiently:

In [11]:
custom_integrator = mm.CustomIntegrator(0.002*u.picoseconds) # 2 fs time step
custom_integrator.addComputePerDof('v', 'v+0.5*dt*f1/m')
for _ in range(4):
    custom_integrator.addComputePerDof('v', 'v+0.5*(dt/4)*f0/m')
    custom_integrator.addComputePerDof('x', 'x+(dt/4)*v')
    custom_integrator.addComputePerDof('v', 'v+0.5*(dt/4)*f0/m')
custom_integrator.addComputePerDof('v', 'v+0.5*dt*f1/m')

print(custom_integrator)

<openmm.openmm.CustomIntegrator; proxy of <Swig Object of type 'OpenMM::CustomIntegrator *' at 0x12ef7ec30> >


## Simulation objects

The Simulation object creates a context that brings everything together.

In [12]:
simulation = app.Simulation(pdb.topology, system, integrator, platform)

You must explicitly set the positions and velocities of the particles after creating the simulation, which is easily done with the PDBFile object defined above and the .setVelocitiesToTemperature() method, respectively.

In [13]:
simulation.context.setPositions(pdb.positions)
simulation.context.setVelocitiesToTemperature(300*u.kelvin)
print(simulation.context.getState(getPositions=True).getPositions(asNumpy=True))
print(simulation.context.getState(getVelocities=True).getVelocities(asNumpy=True))

[[ 0.2     0.1    -0.    ]
 [ 0.2     0.209   0.    ]
 [ 0.1486  0.2454  0.089 ]
 [ 0.1486  0.2454 -0.089 ]
 [ 0.3427  0.2641 -0.    ]
 [ 0.4391  0.1877 -0.    ]
 [ 0.3555  0.397  -0.    ]
 [ 0.2733  0.4556 -0.    ]
 [ 0.4853  0.4614 -0.    ]
 [ 0.5408  0.4316  0.089 ]
 [ 0.5661  0.4221 -0.1232]
 [ 0.5123  0.4521 -0.2131]
 [ 0.663   0.4719 -0.1206]
 [ 0.5809  0.3141 -0.1241]
 [ 0.4713  0.6129  0.    ]
 [ 0.3601  0.6653  0.    ]
 [ 0.5846  0.6835  0.    ]
 [ 0.6737  0.6359 -0.    ]
 [ 0.5846  0.8284  0.    ]
 [ 0.4819  0.8648  0.    ]
 [ 0.636   0.8648  0.089 ]
 [ 0.636   0.8648 -0.089 ]] nm
[[ 3.10881531  0.21540673  0.18806818]
 [-0.28504381  0.21540673 -0.25708699]
 [ 0.94869059  0.07657361  0.51221047]
 [ 0.75432664 -1.51711509 -1.5659346 ]
 [ 0.16859488 -0.14759643  0.32628717]
 [-0.58251636  0.3049909   0.22452708]
 [-1.07328976  0.22295026  0.49015142]
 [-1.8290166  -0.83713073 -1.11393528]
 [ 0.33249724  0.44319458  0.83596101]
 [-2.27136443 -1.55333979  1.79121492]
 [-0.0458328

We can now run the simulation! We first minimize the energy of the system through a geometry relaxation, then we can step through our equations of motion. We'll only run a few steps here and save the state of the system. Once we have the tools to track our data, we'll let it go longer.

In [14]:
print("Minimizing energy...")
simulation.minimizeEnergy(maxIterations=100000,tolerance=0.000001)
print("Done minimizing energy.")
simulation.step(1)

Minimizing energy...
Done minimizing energy.
Done minimizing energy.


## State object

The State object lets you pull information about the state of the system (positions, velocities, forces, energies, etc.). You must provide the specific information you want to be stored in the State, which can then be accessed by calling .getPositions(), .getVelocities(), etc. By default, these are returned as N Vec3 objects for N atoms in your system, but you can get Numpy arrays by setting asNumpy=True in the method argument.

In [15]:
current_state = simulation.context.getState(getPositions=True,
                                            getVelocities=True,
                                            getEnergy=True,
                                            getForces=True,
                                            getParameters=True,
                                            enforcePeriodicBox=True
                                            )
positions = current_state.getPositions()
velocities = current_state.getVelocities(asNumpy=True)
print(positions)
print(velocities)

[Vec3(x=0.2008859006675434, y=0.11842863504607307, z=10.057316175669822), Vec3(x=0.19809007308329524, y=0.21792571491153795, z=10.012891919173006), Vec3(x=0.13446251447139215, y=0.28488719825368564, z=10.070759815874043), Vec3(x=0.1694145495993873, y=0.21041633273397364, z=9.907999958805707), Vec3(x=0.34091094379447345, y=0.26865917158895714, z=10.021883585839683), Vec3(x=0.4271801058232707, y=0.2003369196106844, z=10.071464078824498), Vec3(x=0.360237874767523, y=0.3912385368897973, z=9.973262272711455), Vec3(x=0.28148135313821226, y=0.44114820280556033, z=9.934436565389564), Vec3(x=0.49260180170384993, y=0.459545472476366, z=9.974598380211155), Vec3(x=0.5422926838073658, y=0.4256596667368248, z=10.065502551773081), Vec3(x=0.571705375530753, y=0.41593033346936364, z=9.849528379757109), Vec3(x=0.5171559721394899, y=0.44198109621104775, z=9.758827110595124), Vec3(x=0.671739986806688, y=0.4592190511513425, z=9.84993252238112), Vec3(x=0.5827019613679992, y=0.3074928690559175, z=9.850707927

## Saving states
We can save the State of our simulation as well by calling the saveState method on the simulation. There are actually two options to save at a given point in the simulation: saveState and saveCheckpoint. saveState creates a text file containing positions, velocities, forces, and many other parameters of the simulation. Because it is a text file, it can be used across different machines but can create a large document. Alternatively, saveCheckpoint saves a binary file with this information and should be only used on consistent hardware.

In [16]:
simulation.saveState('progress.state')
pos_check = simulation.context.getState(getPositions=True).getPositions(asNumpy=True) # check that loadState will give the same positions

## Reporters
Reporter objects store simulation data and save it to a file (.log, .pdb, .xtc, ...). You can choose how often you want to save a frame of the simulation (reportInterval), whether to have coordinates enforce periodicity (enforcePeriodicBox for PDBReporter), and what data you would like to keep. The data reporter must be appended to simulation.reporters to save any information about the simulation.

In addition to the one-off save options above, there is also a saveCheckpoint reporter that will automatically create a checkpoint file every $n$ steps in the simulation. There's an optional argument to save the system as a serialized State file (like .saveState) as well.

In [17]:
state_data_reporter = app.StateDataReporter(file='nvt_output.log',
                                            reportInterval=1,
                                            step=True,
                                            time=True,
                                            potentialEnergy=True,
                                            kineticEnergy=True,
                                            totalEnergy=True,
                                            temperature=True,
                                            volume=True,
                                            density=True,
                                            speed=True,
                                            separator=' ')

pdb_reporter = app.PDBReporter(file='nvt_output.pdb',
                               reportInterval=4,
                               enforcePeriodicBox=True)

checkpoint_reporter = app.CheckpointReporter(file='checkpnt.chk',
                                             reportInterval=5,
                                             writeState=False)

simulation.reporters.append(state_data_reporter)
simulation.reporters.append(pdb_reporter)
simulation.reporters.append(checkpoint_reporter)

In [18]:
simulation.step(10)

You should now see three new files in your directory: output.log, output.pdb, and checkpnt.chk.

## Loading states
Let's load the State we saved earlier. We'll first check that our positions have evolved and are not the same as those in the saved State.

In [19]:
pos_check1 = simulation.context.getState(getPositions=True).getPositions(asNumpy=True) # check that positions are different than pos_check
print(np.all(pos_check == pos_check1)) # should be false

False


Now we can load the saved State and check if the positions are the same.

In [20]:
simulation.loadState('progress.state')

pos_check2 = simulation.context.getState(getPositions=True).getPositions(asNumpy=True) # check that loadState will give the same positions
print(np.all(pos_check == pos_check2)) # should be true

True


## (Custom) Forces

We saw with thermostats and barostats that forces could be added outside of the forcefield rules. We can also add whichever forces we see fit using system.addForces(). A link to available forces is here: http://docs.openmm.org/development/api-python/library.html#forces. As we saw an example of adding pre-defined forces to the system above with thermostats and barostats, here we will focus on custom forces. OpenMM lets you write an analytical energy expression and apply the corresponding force to bonds, as an external force on particles, and more. Here we will write a force to trap atoms in our structure in an harmonic well.

There are different kinds of parameters we can set when defining a custom force. Global Parameters apply to all objects experiencing the force, whereas Per Particle Parameters are appropriately named and can have a unique value for every particle. In this case, our spring constant will be global and the positions in which we trap the atoms will be per particle.

In [21]:
print(system.getForces()[-1]) # check the last force in the list, should change once we add custom force
custom_force = mm.CustomExternalForce('k*((x-x0)^2+(y-y0)^2+(z-z0)^2)') # energy function associated with the force we want to add
custom_force.addGlobalParameter('k', 1.0)
custom_force.addPerParticleParameter('x0')
custom_force.addPerParticleParameter('y0')
custom_force.addPerParticleParameter('z0');

<openmm.openmm.CMMotionRemover; proxy of <Swig Object of type 'OpenMM::CMMotionRemover *' at 0x10f1e74b0> >


Next, we want to add each particle to the force as well as the reference positions to each particle. We add particles according to their indices (enumerating over positions is a helpful way to get these), and we add the per particle parameter immediately after. Use the addParticle method on your defined force to do this.

In [22]:
for i, position in enumerate(pos_check):
    custom_force.addParticle(i, position) # add particle to the force

We've created the force, but now we have to add it to the system.

In [23]:
system.addForce(custom_force)
print(system.getForces()[-1]) # check that the custom force is added

<openmm.openmm.CustomExternalForce; proxy of <Swig Object of type 'OpenMM::CustomExternalForce *' at 0x10f1e7300> >


Although we've added the force to the system, we're not done yet. The context doesn't know that we've updated the system, so we must reinitialize it to have everyone on the same page. This is an expensive operation and gets rid of the State information of the system, so we have to be careful when calling it. We've already created a saved state, so let's not worry about creating a new checkpoint. Next, we call reinitialize on the context and reload the State information.

In [24]:
# simulation.saveState('save_before_reinitialize.state')
simulation.context.reinitialize()
simulation.loadState('progress.state')

Let's try running.

In [25]:
simulation.step(100)
print(system.getForces()[-1]) # check that the custom force is still there

<openmm.openmm.CustomExternalForce; proxy of <Swig Object of type 'OpenMM::CustomExternalForce *' at 0x12ea0f180> >


Nice! It runs and the last force in our system is still the external force. Success!

We can also update the PerParticleParameters as we simulate. You may think, "Oh no! If I want to update the forces often, it'll be super expensive to save the State and reinitialize the Context each time." Fear not, for there is a quicker way. Feed the new perParticleParameters to your force object using the setParticleParameters method, then call updateParametersInContext to set them. Let's change the well from the pos_check positions to the pos_check1 positions.

Arguments (in order) for setParticleParameters:
- the index of the parameters you want to set for a given particle
- the index of the particle in your system for which you are setting parameters
- the parameters you would like to set

In [26]:
# Check parameters of the custom force
particle_parameters = []
for i in range(custom_force.getNumParticles()):
    particle_parameters.append(custom_force.getParticleParameters(i))
print(particle_parameters)

# Change parameters of the custom force
for i, position in enumerate(pos_check1):
    custom_force.setParticleParameters(i, i, (position[0], position[1], position[2]))
custom_force.updateParametersInContext(simulation.context)

# Check parameters of the custom force again
particle_parameters = []
for i in range(custom_force.getNumParticles()):
    particle_parameters.append(custom_force.getParticleParameters(i))
print(particle_parameters)

[[0, (0.2008859006675434, 0.11842863504607307, 0.057316175669822285)], [1, (0.19809007308329524, 0.21792571491153795, 0.012891919173006389)], [2, (0.13446251447139215, 0.28488719825368564, 0.07075981587404284)], [3, (0.1694145495993873, 0.21041633273397364, -0.09200004119429353)], [4, (0.34091094379447345, 0.26865917158895714, 0.0218835858396831)], [5, (0.4271801058232707, 0.2003369196106844, 0.0714640788244983)], [6, (0.360237874767523, 0.3912385368897973, -0.026737727288543883)], [7, (0.28148135313821226, 0.44114820280556033, -0.06556343461043566)], [8, (0.49260180170384993, 0.459545472476366, -0.02540161978884391)], [9, (0.5422926838073658, 0.4256596667368248, 0.06550255177308148)], [10, (0.571705375530753, 0.41593033346936364, -0.1504716202428917)], [11, (0.5171559721394899, 0.44198109621104775, -0.24117288940487497)], [12, (0.671739986806688, 0.4592190511513425, -0.15006747761887868)], [13, (0.5827019613679992, 0.3074928690559175, -0.14929207247542997)], [14, (0.4732578338435696, 

The forces have changed!